# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Test7' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeoPackage-iOS-example
  #pod 'geopackage-ios', '~> 3.0.0'
  #pod 'SpatialDBKit'
  pod 'spatialite'
  pod 'FMDB'
end
